package codes;

public class Process {
	public enum Processes{
		//drugInfo
		DRUGINFO_GETALL,
		DRUGINFO_UPDATE,
		DRUGINFO_INSERT,
		DRUGINFO_DELETE,
		DRUGINFO_SELECT,
		//AdminInfo
		ADMININFO_SELECT,
		ADMININFO_DELETE,
		ADMININFO_UPDATE,
		//Storage
		STORAGE_GETALL,
		STORAGE_UPDATE,
		STORAGE_INSERT,
		STORAGE_DELETE,
		STORAGE_SELECT,
		//Sell_rebate
		SELL_GETALL,
		SELL_UPDATE,
		SELL_INSERT,
		SELL_DELETE,
		SELL_SELECT,
		//Patient
		PATIENT_GETALL,
		PATIENT_UPDATE,
		PATIENT_INSERT,
		PATIENT_DELETE,
		PATIENT_SELECT,
		//Manufacture
		MANUFACTURE_GETALL,
		MANUFACTURE_UPDATE,
		MANUFACTURE_INSERT,
		MANUFACTURE_DELETE,
		MANUFACTURE_SELECT
	}
}
